### ISSUE TITLE
Kommas in Titles?

### ISSUE THREAD

**Issue by LenaHenningsen** [LenaHenningsen/ReadingData#27] opened 2017-07-19 09:49 UTC
What happens if a book title contains a comma?
(I am continuing on Shu Ting but slowly)

**Comment by duncdrum** [comment] 2017-07-19 10:26
I m not sure what happens with Chinese full width commas ``，``. If you are editing in libreOffice or MSexcel it should automatically wrap the hole cell in quotation marks without you seeing it, e.g. ``"Books, Typewriters, and other Enumerations"``. Just commit a title with a comma, and check if the file is still properly displayed or not.

**Comment by duncdrum** [comment] 2017-07-19 12:25
duplicate of #25

**Closed by duncdrum** 2017-07-19 12:25 UTC
